// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_BasicLeaseInfo {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.TextBox TextBoxUseOfPremises;
	
	protected System.Web.UI.WebControls.TextBox TextBoxExlusiveRights;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRestrictionOfUse;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonSubmit;
}
