// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_BillingMenu {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.RadioButton RadioButtonBillingSame;
	
	protected System.Web.UI.WebControls.RadioButton RadioButtonBillingNotSame;
	
	protected System.Web.UI.WebControls.TextBox TextBoxBillName;
	
	protected System.Web.UI.WebControls.TextBox TextBoxBillingAddress;
	
	protected System.Web.UI.WebControls.TextBox TextBoxBillingCity;
	
	protected System.Web.UI.WebControls.TextBox TextBoxBillingState;
	
	protected System.Web.UI.WebControls.TextBox TextBoxBillingZip;
	
	protected Tenant_PersonControl BillingContact;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
}
