// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_Documents {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Panel PanelDocuments;
	
	protected Documents_DocumentsControl DocumentsTenant;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected Documents_DocumentsControl DocumentsIC;
}
