// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_Insurance {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.TextBox TextBoxICBeginDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxICEndDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxInsured;
	
	protected System.Web.UI.WebControls.TextBox TextBoxAdditionalInsured;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
	
	protected Documents_DocumentsControl DocumentsIC;
}
