// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_Lease {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Panel PanelLeaseTerm;
	
	protected System.Web.UI.WebControls.TextBox TextBoxLeaseDocumentDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxLeaseCommencement;
	
	protected System.Web.UI.WebControls.TextBox TextBoxLeaseExpiration;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonSubmit;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListRentCommencementType;
	
	protected System.Web.UI.WebControls.TextBox TextBoxDate;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonRentCommencementAdd;
	
	protected System.Web.UI.WebControls.Panel PanelOptionPeriods;
	
	protected System.Web.UI.WebControls.TextBox TextBoxNumberOptions;
	
	protected System.Web.UI.WebControls.TextBox TextBoxOptionLength;
	
	protected System.Web.UI.WebControls.TextBox TextBoxOptionExercisedBy;
	
	protected System.Web.UI.WebControls.TextBox TextBoxOptionNotificationDate;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonOptions;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.TextBox TextBoxLeaseNotes;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonLeaseNotes;
}
