// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QuickPMWebsite {
	
	
	public partial class Occupancy {
		
		protected System.Web.UI.WebControls.TextBox TextBoxUnitNumber;
		
		protected System.Web.UI.WebControls.TextBox TextBoxUnitSqFt;
		
		protected System.Web.UI.WebControls.Button ButtonAddNewUnit;
		
		protected System.Web.UI.WebControls.DropDownList DropDownListSelectUnit;
		
		protected System.Web.UI.WebControls.TextBox TextBoxStartDate;
		
		protected System.Web.UI.WebControls.TextBox TextBoxEndDate;
		
		protected System.Web.UI.WebControls.Button ButtonAddUnit;
	}
}
