// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_SecurityDeposit {
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.TextBox TextBoxSecurityDepositAmount;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit1;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.TextBox TextBoxSecurityDepositCheckNumber;
	
	protected System.Web.UI.WebControls.TextBox TextBoxSecurityDepositCheckAmount;
	
	protected System.Web.UI.WebControls.Panel Panel3;
	
	protected System.Web.UI.WebControls.TextBox TextBoxSecurityDepositCheckDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxSecurityDepositCheckReceivedDate;
	
	protected System.Web.UI.WebControls.Panel Panel4;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRequiredRefundDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRequiredRefundAmount;
	
	protected System.Web.UI.WebControls.Button ButtonRequiredRefund;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRefundCheckNumber;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRefundAmount;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRefundDate;
	
	protected System.Web.UI.WebControls.Button ButtonAddRefund;
	
	protected System.Web.UI.WebControls.TextBox TextBoxNotes;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
}
