// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_Tenant {
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.TextBox TextBoxTenantId;
	
	protected System.Web.UI.WebControls.TextBox TextBoxName;
	
	protected System.Web.UI.WebControls.Panel Panel4;
	
	protected System.Web.UI.WebControls.RadioButton RadioButtonActive;
	
	protected System.Web.UI.WebControls.RadioButton RadioButtonInactive;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.TextBox TextBoxLocation;
	
	protected System.Web.UI.WebControls.TextBox TextBoxCity;
	
	protected System.Web.UI.WebControls.TextBox TextBoxState;
	
	protected System.Web.UI.WebControls.TextBox TextBoxZip;
	
	protected System.Web.UI.WebControls.TextBox TextBoxPhone;
	
	protected System.Web.UI.WebControls.TextBox TextBoxBillingEmail;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
	
	protected System.Web.UI.UserControl Units;
}
