// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QuickPMWebsite {
	
	
	public partial class FindVolunteers {
		
		protected System.Web.UI.WebControls.Content headContent;
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.TextBox Name;
		
		protected System.Web.UI.WebControls.TextBox Employer;
		
		protected System.Web.UI.WebControls.TextBox Interest;
		
		protected System.Web.UI.WebControls.Button Search;
		
		public new BaseMaster Master {
			get {
				return ((BaseMaster)(base.Master));
			}
		}
	}
}
