// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Billings_BillingsControl {
	
	protected System.Web.UI.WebControls.DropDownList DropDownListPropertyId;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListMonth;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListYear;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
	
	protected System.Web.UI.WebControls.Button ButtonEmail;
}
