// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Billings_BillingChanges {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListProperty;
	
	protected System.Web.UI.WebControls.TextBox TextBoxDays;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.CheckBoxList ListBoxRentTypes;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
}
