// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Reports_CashFlowIncome {
	
	protected System.Web.UI.WebControls.Label Label1;
	
	protected System.Web.UI.WebControls.DropDownList PropertyList;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.Label Label2;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListBeginYear;
	
	protected System.Web.UI.WebControls.Label Label3;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListBeginMonth;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.Label Label4;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListEndYear;
	
	protected System.Web.UI.WebControls.Label Label5;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListEndMonth;
	
	protected System.Web.UI.WebControls.Button ButtonGenerateChart;
	
	protected System.Web.UI.WebControls.Panel Panel3;
	
	protected System.Web.UI.WebControls.Panel Panel4;
}
