// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Reports_Property_InsuranceCertificateReport {
	
	protected System.Web.UI.WebControls.DropDownList DropDownListProperty;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonSubmit;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonMissing;
}
