// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Property_ExpenseItem {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.TextBox TextBoxExpenseName;
	
	protected System.Web.UI.WebControls.TextBox TextBoxCOA;
	
	protected System.Web.UI.WebControls.CheckBox CheckBoxSubaccount;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListAccounts;
	
	protected System.Web.UI.WebControls.TextBox TextBoxIncrease;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonIncrease;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonDecrease;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonSubmit;
}
