// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Property_BudgetDates {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListBeginMonth;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListBeginYear;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListEndMonth;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListEndYear;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
	
	protected System.Web.UI.WebControls.Panel Panel3;
	
	protected System.Web.UI.WebControls.Panel Panel4;
	
	protected System.Web.UI.WebControls.Panel Panel5;
}
