// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class CashJournal_EditDepositEntry {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListTenant;
	
	protected System.Web.UI.WebControls.TextBox TextBoxCheckDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxReceivedDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxCheckNumber;
	
	protected System.Web.UI.WebControls.TextBox TextBoxAmount;
	
	protected System.Web.UI.WebControls.TextBox TextBoxNotes;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonSubmit;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonCancel;
}
