// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Property_PropertyControl {
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.TextBox TextBoxPropertyId;
	
	protected System.Web.UI.WebControls.TextBox TextBoxPropertyName;
	
	protected System.Web.UI.WebControls.Panel Panel4;
	
	protected System.Web.UI.WebControls.RadioButton RadioButtonActive;
	
	protected System.Web.UI.WebControls.RadioButton RadioButtonInactive;
	
	protected System.Web.UI.WebControls.TextBox TextBoxLegalName;
	
	protected System.Web.UI.WebControls.TextBox TextBoxPhysicalAddress;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRentTypeName;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRentTypeChartOfAccount;
	
	protected System.Web.UI.WebControls.Button ButtonAddRentType;
	
	protected System.Web.UI.WebControls.Panel Panel3;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitName;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitAddress;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitCity;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitState;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitZip;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitTelephone;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitFax;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRemitEmail;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
}
