// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QuickPMWebsite.Property {
	
	
	public partial class ServiceRequests {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected CalendarControl_CalendarControl ucCalendar;
		
		protected System.Web.UI.WebControls.LinkButton LinkButtonAddWorkOrder;
	}
}
