// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Property_Units {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListTenant;
	
	protected System.Web.UI.WebControls.TextBox TextBoxUnitNumber;
	
	protected System.Web.UI.WebControls.TextBox TextBoxSqFt;
	
	protected System.Web.UI.WebControls.TextBox TextBoxAreaSize;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonListHasOutside;
	
	protected System.Web.UI.WebControls.TextBox TextBoxSqFtOutside;
	
	protected System.Web.UI.WebControls.TextBox TextBoxOutsideAreaSize;
	
	protected System.Web.UI.WebControls.TextBox TextBoxNotes;
	
	protected System.Web.UI.WebControls.Button ButtonAdd;
}
