// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Notices_GenerateNotice {
	
	protected System.Web.UI.WebControls.DropDownList DropDownListTenants;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListRentTypes;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListDays;
	
	protected System.Web.UI.WebControls.TextBox TextBoxCreditorName;
	
	protected System.Web.UI.WebControls.TextBox TextBoxDeliveryLocation;
	
	protected System.Web.UI.WebControls.TextBox TextBoxAgentTelephone;
	
	protected System.Web.UI.WebControls.Button ButtonCreateNotice;
}
