// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class CreateAccount_Setup {
	
	protected System.Web.UI.WebControls.Panel Panel1;
	
	protected System.Web.UI.WebControls.Label Label7;
	
	protected System.Web.UI.WebControls.TextBox TextBoxAccountName;
	
	protected System.Web.UI.WebControls.Panel Panel3;
	
	protected System.Web.UI.WebControls.Label Label3;
	
	protected System.Web.UI.WebControls.TextBox TextBoxEmail;
	
	protected System.Web.UI.WebControls.Label Label4;
	
	protected System.Web.UI.WebControls.TextBox TextBoxPassword;
	
	protected System.Web.UI.WebControls.Label Label5;
	
	protected System.Web.UI.WebControls.TextBox TextBoxRepeatPassword;
	
	protected System.Web.UI.WebControls.LinkButton LinkButtonCreateAccount;
}
