// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Insurance_InsurancePolicy {
	
	protected System.Web.UI.WebControls.TextBox TextBoxInsurer;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListPolicyDescription;
	
	protected System.Web.UI.WebControls.TextBox TextBoxPolicyNumber;
	
	protected System.Web.UI.WebControls.TextBox TextBoxBeginPeriod;
	
	protected System.Web.UI.WebControls.TextBox TextBoxEndPeriod;
	
	protected System.Web.UI.WebControls.TextBox TextBoxLimitAmount;
	
	protected System.Web.UI.WebControls.DropDownList DropDownListLimitDescription;
	
	protected System.Web.UI.WebControls.Button ButtonSubmit;
}
