// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QuickPMWebsite.WorkOrders {
	
	
	public partial class EditMaterialLineItem {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescription;
		
		protected System.Web.UI.WebControls.TextBox TextBoxQuantityUsed;
		
		protected System.Web.UI.WebControls.TextBox TextBoxPurchaseCost;
		
		protected System.Web.UI.WebControls.TextBox TextBoxChargeback;
		
		protected System.Web.UI.WebControls.LinkButton LinkButtonFinish;
	}
}
