// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QuickPMWebsite.WorkOrders {
	
	
	public partial class WorkOrderControl {
		
		protected System.Web.UI.WebControls.TextBox TextBoxRequestDate;
		
		protected System.Web.UI.WebControls.DropDownList DropDownTime;
		
		protected System.Web.UI.WebControls.TextBox TextBoxReceivedBy;
		
		protected System.Web.UI.WebControls.DropDownList DropDownListTenant;
		
		protected System.Web.UI.WebControls.TextBox TextBoxContactName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxContactPhone;
		
		protected System.Web.UI.WebControls.TextBox TextBoxOtherAddress;
		
		protected System.Web.UI.WebControls.TextBox TextBoxOtherCity;
		
		protected System.Web.UI.WebControls.TextBox TextBoxOtherState;
		
		protected System.Web.UI.WebControls.TextBox TextBoxOtherKeyContact;
		
		protected System.Web.UI.WebControls.TextBox TextBoxOtherNumber;
		
		protected System.Web.UI.WebControls.TextBox TextBoxAreaOfWork;
		
		protected System.Web.UI.WebControls.TextBox TextBoxRequest;
		
		protected System.Web.UI.WebControls.TextBox TextBoxContractor;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDateContacted;
		
		protected System.Web.UI.WebControls.TextBox TextBoxContractorContactName;
		
		protected System.Web.UI.WebControls.DropDownList DropDownTime2;
		
		protected System.Web.UI.WebControls.TextBox TextBoxPhone;
		
		protected System.Web.UI.WebControls.CheckBox CheckBoxCompleted;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompletionDate;
		
		protected System.Web.UI.WebControls.TextBox TextBoxWorkDone;
		
		protected System.Web.UI.WebControls.TextBox TextBoxNotes;
		
		protected System.Web.UI.WebControls.LinkButton LinkButtonDone;
		
		protected System.Web.UI.WebControls.LinkButton LinkButtonCancel;
	}
}
