// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class BaseMaster {
	
	protected System.Web.UI.WebControls.ContentPlaceHolder head;
	
	protected System.Web.UI.HtmlControls.HtmlForm basemasterform;
	
	protected BottomBar topbar;
	
	protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
	
	protected BottomBar BottomBar;
}
