// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Login {
	
	protected System.Web.UI.WebControls.TextBox TextBoxEmail;
	
	protected System.Web.UI.WebControls.TextBox TextBoxPassword;
	
	protected System.Web.UI.WebControls.CheckBox CheckBoxRemember;
	
	protected System.Web.UI.WebControls.Button ButtonLogin;
}
