// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Tenant_PersonControl {
	
	protected System.Web.UI.WebControls.Panel Panel3;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactName;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactOfficePhone;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactTitle;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactCellPhone;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactHomePhone;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactFax;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactEmail;
	
	protected System.Web.UI.WebControls.TextBox TextBoxContactAddress;
}
