// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class AddCheck {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.UserControl MainMenu;
	
	protected System.Web.UI.WebControls.TextBox checkNumber;
	
	protected System.Web.UI.WebControls.TextBox checkAmount;
	
	protected System.Web.UI.WebControls.TextBox checkDate;
	
	protected System.Web.UI.WebControls.TextBox receivedDate;
	
	protected System.Web.UI.WebControls.Button buttonAddCheck;
}
