// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Checks_ViewCheck {
	
	protected System.Web.UI.UserControl CheckMenu;
	
	protected System.Web.UI.WebControls.TextBox CheckNumber;
	
	protected System.Web.UI.WebControls.TextBox TextBoxCheckDate;
	
	protected System.Web.UI.WebControls.TextBox TextBoxReceivedDate;
	
	protected System.Web.UI.WebControls.TextBox CheckAmount;
	
	protected System.Web.UI.WebControls.LinkButton UnapplyCheck;
	
	protected System.Web.UI.WebControls.LinkButton ApplyCheck;
	
	protected System.Web.UI.WebControls.TextBox Memo;
	
	protected System.Web.UI.WebControls.LinkButton SubmitButton;
	
	protected System.Web.UI.WebControls.LinkButton ButtonDeleteCheck;
}
