// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class ManageUsers_AddUser {
	
	protected System.Web.UI.WebControls.Label Label1;
	
	protected System.Web.UI.WebControls.TextBox TextBoxEmailAddress;
	
	protected System.Web.UI.WebControls.Label Label2;
	
	protected System.Web.UI.WebControls.TextBox TextBoxName;
	
	protected System.Web.UI.WebControls.Button ButtonAddUser;
}
