// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QuickPMWebsite.Views.Tenants {
	
	
	public partial class DeleteBilling {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
	}
}
